<?php
session_start(); require dirname(__DIR__).'/config.php';
if(isset($_GET['logout'])){session_destroy();header('Location:/admin/');exit;}
if(!isset($_SESSION['admin_id'])){
 $err=''; if($_SERVER['REQUEST_METHOD']==='POST'){try{$st=db()->prepare('SELECT * FROM admins WHERE username=? LIMIT 1');$st->execute([$_POST['username']??'']);$a=$st->fetch();if($a&&password_verify($_POST['password']??'',$a['password_hash'])){$_SESSION['admin_id']=$a['id'];header('Location:/admin/');exit;}else{$err='بيانات الدخول غير صحيحة';}}catch(Throwable $e){$err='قاعدة البيانات غير مهيأة';}}
 ?><!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>LIVO Admin</title><style>body{font-family:Arial;background:#101014;color:white}.box{max-width:420px;margin:100px auto;background:#1d1d24;padding:25px;border-radius:14px}input{width:100%;box-sizing:border-box;padding:12px;margin:8px 0;background:#111;color:#fff;border:1px solid #444;border-radius:8px}button{padding:12px;width:100%;background:#fe2c55;color:#fff;border:0;border-radius:8px}</style></head><body><div class="box"><h2>LIVO Admin</h2><?php if($err)echo '<p>'.htmlspecialchars($err).'</p>';?><form method="post"><input name="username" placeholder="اسم المستخدم"><input type="password" name="password" placeholder="كلمة المرور"><button>دخول</button></form></div></body></html><?php exit;
}
if(isset($_GET['block'])){db()->prepare('UPDATE users SET is_blocked=1 WHERE id=?')->execute([(int)$_GET['block']]);header('Location:/admin/');exit;}
if(isset($_GET['unblock'])){db()->prepare('UPDATE users SET is_blocked=0 WHERE id=?')->execute([(int)$_GET['unblock']]);header('Location:/admin/');exit;}
if(isset($_GET['delete'])){db()->prepare('DELETE FROM users WHERE id=?')->execute([(int)$_GET['delete']]);header('Location:/admin/');exit;}
if(isset($_GET['endlive'])){db()->prepare('UPDATE live_rooms SET status="ended",ended_at=NOW() WHERE id=?')->execute([(int)$_GET['endlive']]);header('Location:/admin/');exit;}
if(isset($_GET['closereport'])){db()->prepare('UPDATE reports SET status="closed" WHERE id=?')->execute([(int)$_GET['closereport']]);header('Location:/admin/');exit;}
$users=db()->query('SELECT * FROM users ORDER BY id DESC LIMIT 300')->fetchAll();
$lives=db()->query('SELECT l.*,u.name host_name FROM live_rooms l JOIN users u ON u.id=l.host_id ORDER BY l.id DESC LIMIT 100')->fetchAll();
$reports=db()->query('SELECT r.*,u1.name reporter_name,u2.name target_name FROM reports r JOIN users u1 ON u1.id=r.reporter_id JOIN users u2 ON u2.id=r.target_user_id ORDER BY r.id DESC LIMIT 100')->fetchAll();
$calls=db()->query('SELECT c.id,c.status,c.created_at,u1.name caller_name,u2.name callee_name FROM calls c JOIN users u1 ON u1.id=c.caller_id JOIN users u2 ON u2.id=c.callee_id ORDER BY c.id DESC LIMIT 100')->fetchAll();
?><!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>LIVO Admin</title><style>body{font-family:Arial;background:#0f1014;color:#eee;margin:0}.wrap{max-width:1250px;margin:auto;padding:24px}.top{display:flex;justify-content:space-between;align-items:center}.card{background:#191b22;border-radius:12px;padding:18px;margin:18px 0;overflow:auto}table{width:100%;border-collapse:collapse;min-width:650px}th,td{padding:10px;border-bottom:1px solid #30323a;text-align:right}a{color:#9cbcff}.danger{color:#ff7d7d}.ok{color:#7dffad}.stats{display:flex;gap:12px;flex-wrap:wrap}.stat{background:#191b22;padding:14px 20px;border-radius:12px}</style></head><body><div class="wrap"><div class="top"><h1>LIVO Admin</h1><a href="?logout=1">تسجيل الخروج</a></div><div class="stats"><div class="stat">المستخدمون: <?=count($users)?></div><div class="stat">البثوث: <?=count($lives)?></div><div class="stat">البلاغات: <?=count($reports)?></div><div class="stat">المكالمات: <?=count($calls)?></div></div><div class="card"><h2>المستخدمون</h2><table><tr><th>ID</th><th>الاسم</th><th>البريد</th><th>الحالة</th><th>الإجراء</th></tr><?php foreach($users as $u):?><tr><td><?=$u['id']?></td><td><?=htmlspecialchars($u['name'])?></td><td><?=htmlspecialchars($u['email'])?></td><td><?=$u['is_blocked']?'محظور':'فعال'?></td><td><?php if($u['is_blocked']):?><a href="?unblock=<?=$u['id']?>">فك الحظر</a><?php else:?><a href="?block=<?=$u['id']?>">حظر</a><?php endif;?> | <a class="danger" onclick="return confirm('حذف؟')" href="?delete=<?=$u['id']?>">حذف</a></td></tr><?php endforeach;?></table></div><div class="card"><h2>البثوث</h2><table><tr><th>ID</th><th>المضيف</th><th>العنوان</th><th>الحالة</th><th>الإجراء</th></tr><?php foreach($lives as $l):?><tr><td><?=$l['id']?></td><td><?=htmlspecialchars($l['host_name'])?></td><td><?=htmlspecialchars($l['title'])?></td><td><?=$l['status']?></td><td><?php if($l['status']==='live'):?><a href="?endlive=<?=$l['id']?>">إيقاف البث</a><?php endif;?></td></tr><?php endforeach;?></table></div><div class="card"><h2>المكالمات</h2><table><tr><th>ID</th><th>من</th><th>إلى</th><th>الحالة</th><th>الوقت</th></tr><?php foreach($calls as $c):?><tr><td><?=$c['id']?></td><td><?=htmlspecialchars($c['caller_name'])?></td><td><?=htmlspecialchars($c['callee_name'])?></td><td><?=$c['status']?></td><td><?=$c['created_at']?></td></tr><?php endforeach;?></table></div><div class="card"><h2>البلاغات</h2><table><tr><th>ID</th><th>المبلّغ</th><th>المستخدم</th><th>السبب</th><th>الحالة</th><th></th></tr><?php foreach($reports as $r):?><tr><td><?=$r['id']?></td><td><?=htmlspecialchars($r['reporter_name'])?></td><td><?=htmlspecialchars($r['target_name'])?></td><td><?=htmlspecialchars($r['reason'])?></td><td><?=$r['status']?></td><td><?php if($r['status']==='open'):?><a href="?closereport=<?=$r['id']?>">إغلاق البلاغ</a><?php endif;?></td></tr><?php endforeach;?></table></div></div></body></html>
