import 'dart:async';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter_webrtc/flutter_webrtc.dart';
import '../services/api.dart';
class CallScreen extends StatefulWidget{final Map<String,dynamic>? other;final Map<String,dynamic>? incomingCall;const CallScreen({super.key,this.other,this.incomingCall});@override State<CallScreen>createState()=>_CallScreenState();}
class _CallScreenState extends State<CallScreen>{final local=RTCVideoRenderer(),remote=RTCVideoRenderer();RTCPeerConnection? pc;MediaStream? stream;Timer? poll;int? callId;String status='جاري الاتصال...';
Future<void> waitIce() async { await Future.delayed(const Duration(seconds:2)); }
@override void initState(){super.initState();init();}
Future<void>init()async{try{await local.initialize();await remote.initialize();stream=await navigator.mediaDevices.getUserMedia({'audio':true,'video':{'facingMode':'user'}});local.srcObject=stream;pc=await createPeerConnection({'iceServers':[{'urls':'stun:stun.l.google.com:19302'}]});for(final t in stream!.getTracks()){pc!.addTrack(t,stream!);}pc!.onTrack=(e){if(e.streams.isNotEmpty){remote.srcObject=e.streams.first;if(mounted)setState(()=>status='متصل');}};if(widget.incomingCall!=null){await answerIncoming();}else{await startOutgoing();}}catch(e){if(mounted)setState(()=>status='تعذر بدء المكالمة');}}
Future<void>startOutgoing()async{final offer=await pc!.createOffer();await pc!.setLocalDescription(offer);await waitIce();final desc=await pc!.getLocalDescription();final j=await Api.request('/call/start',method:'POST',body:{'user_id':widget.other!['id'],'offer':{'sdp':desc!.sdp,'type':desc.type}});callId=int.parse(j['call_id'].toString());poll=Timer.periodic(const Duration(seconds:2),(_)=>pollStatus());}
Future<void>answerIncoming()async{callId=int.parse(widget.incomingCall!['id'].toString());final raw=widget.incomingCall!['offer'];final o=raw is String?jsonDecode(raw):raw;await pc!.setRemoteDescription(RTCSessionDescription(o['sdp'],o['type']));final ans=await pc!.createAnswer();await pc!.setLocalDescription(ans);await waitIce();final d=await pc!.getLocalDescription();await Api.request('/call/answer',method:'POST',body:{'call_id':callId,'answer':{'sdp':d!.sdp,'type':d.type}});if(mounted)setState(()=>status='متصل');}
Future<void>pollStatus()async{if(callId==null)return;try{final j=await Api.request('/call/status?id=$callId');final c=j['call'];if(c==null)return;if(c['status']=='active'&&c['answer']!=null&&remote.srcObject==null){final a=c['answer'] is String?jsonDecode(c['answer']):c['answer'];await pc!.setRemoteDescription(RTCSessionDescription(a['sdp'],a['type']));if(mounted)setState(()=>status='متصل');}if(c['status']=='ended'||c['status']=='rejected'){if(mounted)Navigator.pop(context);}}catch(_){}}
Future<void>end()async{try{if(callId!=null)await Api.request('/call/end',method:'POST',body:{'call_id':callId});}catch(_){}if(mounted)Navigator.pop(context);}
@override void dispose(){poll?.cancel();for(final t in stream?.getTracks()??[]){t.stop();}pc?.close();local.dispose();remote.dispose();super.dispose();}
@override Widget build(BuildContext context)=>Scaffold(backgroundColor:Colors.black,body:Stack(children:[Positioned.fill(child:RTCVideoView(remote,objectFit:RTCVideoViewObjectFit.RTCVideoViewObjectFitCover)),Positioned(top:55,right:16,width:110,height:160,child:ClipRRect(borderRadius:BorderRadius.circular(16),child:RTCVideoView(local,mirror:true,objectFit:RTCVideoViewObjectFit.RTCVideoViewObjectFitCover))),Positioned(top:55,left:20,child:Text(status,style:const TextStyle(color:Colors.white,fontSize:16,fontWeight:FontWeight.bold))),Positioned(bottom:45,left:0,right:0,child:Center(child:FloatingActionButton(backgroundColor:Colors.red,onPressed:end,child:const Icon(Icons.call_end,color:Colors.white))))]));}
