import 'dart:async';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter_webrtc/flutter_webrtc.dart';
import '../services/api.dart';
class LiveRoomScreen extends StatefulWidget{final Map<String,dynamic> room;final bool isHost;const LiveRoomScreen({super.key,required this.room,required this.isHost});@override State<LiveRoomScreen>createState()=>_LiveRoomScreenState();}
class _LiveRoomScreenState extends State<LiveRoomScreen>{final video=RTCVideoRenderer();MediaStream? local;RTCPeerConnection? viewerPc;final Map<int,RTCPeerConnection> hostPeers={};Timer? poll;int lastSignal=0;List comments=[];final text=TextEditingController();String status='جاري الاتصال...';
Future<RTCPeerConnection> makePc()async=>createPeerConnection({'iceServers':[{'urls':'stun:stun.l.google.com:19302'}]});
Future<void> waitIce(RTCPeerConnection pc) async { await Future.delayed(const Duration(seconds:2)); }
@override void initState(){super.initState();init();}
Future<void>init()async{await video.initialize();if(widget.isHost){local=await navigator.mediaDevices.getUserMedia({'audio':true,'video':{'facingMode':'user'}});video.srcObject=local;if(mounted)setState(()=>status='أنت على الهواء');}else{await Api.request('/live/join',method:'POST',body:{'room_id':widget.room['id']});viewerPc=await makePc();viewerPc!.onTrack=(e){if(e.streams.isNotEmpty){video.srcObject=e.streams.first;if(mounted)setState(()=>status='LIVE');}};if(mounted)setState(()=>status='بانتظار الفيديو...');}poll=Timer.periodic(const Duration(seconds:2),(_){pollSignals();loadComments();});}
Future<void>pollSignals()async{try{final j=await Api.request('/live/signals?room_id=${widget.room['id']}&after=$lastSignal');for(final raw in List.from(j['signals']??[])){final s=Map<String,dynamic>.from(raw);lastSignal=int.parse(s['id'].toString());final type=s['type'].toString();final sender=int.parse(s['sender_id'].toString());final payload=s['payload'] is String?jsonDecode(s['payload']):s['payload'];if(widget.isHost&&type=='viewer_join'){await offerTo(sender);}else if(widget.isHost&&type=='answer'){final pc=hostPeers[sender];if(pc!=null)await pc.setRemoteDescription(RTCSessionDescription(payload['sdp'],payload['type']));}else if(!widget.isHost&&type=='offer'){await viewerPc!.setRemoteDescription(RTCSessionDescription(payload['sdp'],payload['type']));final ans=await viewerPc!.createAnswer();await viewerPc!.setLocalDescription(ans);await waitIce(viewerPc!);final d=await viewerPc!.getLocalDescription();await Api.request('/live/signal',method:'POST',body:{'room_id':widget.room['id'],'target_id':sender,'type':'answer','payload':{'sdp':d!.sdp,'type':d.type}});}}}catch(_){}}
Future<void>offerTo(int viewerId)async{if(hostPeers.containsKey(viewerId))return;final pc=await makePc();hostPeers[viewerId]=pc;for(final t in local!.getTracks()){pc.addTrack(t,local!);}final offer=await pc.createOffer();await pc.setLocalDescription(offer);await waitIce(pc);final d=await pc.getLocalDescription();await Api.request('/live/signal',method:'POST',body:{'room_id':widget.room['id'],'target_id':viewerId,'type':'offer','payload':{'sdp':d!.sdp,'type':d.type}});}
Future<void>loadComments()async{try{final j=await Api.request('/live/comments?room_id=${widget.room['id']}');if(mounted)setState(()=>comments=List.from(j['comments']??[]));}catch(_){}}
Future<void>sendComment()async{final v=text.text.trim();if(v.isEmpty)return;text.clear();await Api.request('/live/comment',method:'POST',body:{'room_id':widget.room['id'],'body':v});await loadComments();}
Future<void>end()async{try{if(widget.isHost)await Api.request('/live/end',method:'POST',body:{'room_id':widget.room['id']});}catch(_){}if(mounted)Navigator.pop(context);}
@override void dispose(){poll?.cancel();for(final t in local?.getTracks()??[]){t.stop();}viewerPc?.close();for(final p in hostPeers.values){p.close();}video.dispose();text.dispose();super.dispose();}
@override Widget build(BuildContext context)=>Scaffold(backgroundColor:Colors.black,body:SafeArea(child:Stack(children:[Positioned.fill(child:RTCVideoView(video,mirror:widget.isHost,objectFit:RTCVideoViewObjectFit.RTCVideoViewObjectFitCover)),Positioned(top:10,left:10,right:10,child:Row(children:[Container(padding:const EdgeInsets.symmetric(horizontal:12,vertical:8),decoration:BoxDecoration(color:Colors.black54,borderRadius:BorderRadius.circular(14)),child:Text('${widget.room['title']??'LIVE'} • $status',style:const TextStyle(color:Colors.white))),const Spacer(),IconButton.filled(onPressed:end,icon:const Icon(Icons.close))])),Positioned(left:12,right:12,bottom:72,height:190,child:ListView.builder(itemCount:comments.length,itemBuilder:(_,i){final c=comments[i];return Padding(padding:const EdgeInsets.symmetric(vertical:3),child:Text('${c['name']}: ${c['body']}',style:const TextStyle(color:Colors.white,shadows:[Shadow(color:Colors.black,blurRadius:4)])));})),Positioned(left:10,right:10,bottom:10,child:Row(children:[Expanded(child:TextField(controller:text,style:const TextStyle(color:Colors.white),decoration:InputDecoration(hintText:'اكتب تعليق...',hintStyle:const TextStyle(color:Colors.white70),filled:true,fillColor:Colors.black54,border:OutlineInputBorder(borderRadius:BorderRadius.circular(24),borderSide:BorderSide.none)))),const SizedBox(width:8),IconButton.filled(onPressed:sendComment,icon:const Icon(Icons.send))]))])));
}
