import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import '../brand.dart';
import '../services/api.dart';
import '../widgets/avatar.dart';
import 'auth_screen.dart';
class ProfileScreen extends StatefulWidget{const ProfileScreen({super.key});@override State<ProfileScreen>createState()=>_ProfileScreenState();}
class _ProfileScreenState extends State<ProfileScreen>{Map<String,dynamic>? user;@override void initState(){super.initState();load();}Future<void>load()async{try{final j=await Api.request('/me');if(mounted)setState(()=>user=Map<String,dynamic>.from(j['user']));}catch(_){}}Future<void>photo()async{final x=await ImagePicker().pickImage(source:ImageSource.gallery,imageQuality:85);if(x!=null){await Api.uploadAvatar(File(x.path));await load();}}Future<void>edit()async{if(user==null)return;final n=TextEditingController(text:user!['name']??''),b=TextEditingController(text:user!['bio']??'');final ok=await showDialog<bool>(context:context,builder:(ctx)=>AlertDialog(title:const Text('تعديل الحساب'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'الاسم')),const SizedBox(height:10),TextField(controller:b,maxLines:3,decoration:const InputDecoration(labelText:'نبذة'))]),actions:[TextButton(onPressed:()=>Navigator.pop(ctx,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(ctx,true),child:const Text('حفظ'))]));if(ok==true){await Api.request('/profile',method:'POST',body:{'name':n.text,'bio':b.text});await load();}}Future<void>logout()async{await Api.logout();if(mounted)Navigator.pushAndRemoveUntil(context,MaterialPageRoute(builder:(_)=>const AuthScreen()),(_)=>false);}@override Widget build(BuildContext context){if(user==null)return const Center(child:CircularProgressIndicator());return Scaffold(appBar:AppBar(title:const Text(Brand.name),actions:[IconButton(onPressed:logout,icon:const Icon(Icons.logout))]),body:Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(children:[GestureDetector(onTap:photo,child:Stack(children:[Avatar(url:user!['avatar'],radius:62),const Positioned(right:0,bottom:0,child:CircleAvatar(child:Icon(Icons.camera_alt)))])),const SizedBox(height:14),Text(user!['name']??'',style:const TextStyle(fontSize:26,fontWeight:FontWeight.bold)),Text(user!['email']??''),const SizedBox(height:10),Text(user!['bio']??''),const SizedBox(height:20),OutlinedButton.icon(onPressed:edit,icon:const Icon(Icons.edit),label:const Text('تعديل الحساب'))]))));}}
