CREATE TABLE IF NOT EXISTS users (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL,
 email VARCHAR(190) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 bio VARCHAR(500) DEFAULT '',
 avatar VARCHAR(255) DEFAULT NULL,
 is_blocked TINYINT(1) NOT NULL DEFAULT 0,
 created_at DATETIME NOT NULL,
 updated_at DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS auth_tokens (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id INT UNSIGNED NOT NULL,
 token VARCHAR(128) NOT NULL UNIQUE,
 expires_at DATETIME NOT NULL,
 created_at DATETIME NOT NULL,
 INDEX(user_id), INDEX(token)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS follows (
 follower_id INT UNSIGNED NOT NULL,
 following_id INT UNSIGNED NOT NULL,
 created_at DATETIME NOT NULL,
 PRIMARY KEY(follower_id,following_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS conversations (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user1_id INT UNSIGNED NOT NULL,
 user2_id INT UNSIGNED NOT NULL,
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 UNIQUE KEY pair_unique(user1_id,user2_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS messages (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 conversation_id BIGINT UNSIGNED NOT NULL,
 sender_id INT UNSIGNED NOT NULL,
 body TEXT NOT NULL,
 created_at DATETIME NOT NULL,
 INDEX(conversation_id), INDEX(sender_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS live_rooms (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 host_id INT UNSIGNED NOT NULL,
 title VARCHAR(180) NOT NULL,
 room_key VARCHAR(128) NOT NULL,
 status ENUM('live','ended') NOT NULL DEFAULT 'live',
 created_at DATETIME NOT NULL,
 ended_at DATETIME DEFAULT NULL,
 INDEX(host_id), INDEX(status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS live_signals (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 room_id BIGINT UNSIGNED NOT NULL,
 sender_id INT UNSIGNED NOT NULL,
 target_id INT UNSIGNED DEFAULT NULL,
 type VARCHAR(40) NOT NULL,
 payload LONGTEXT DEFAULT NULL,
 created_at DATETIME NOT NULL,
 INDEX(room_id), INDEX(target_id), INDEX(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS live_comments (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 room_id BIGINT UNSIGNED NOT NULL,
 user_id INT UNSIGNED NOT NULL,
 body VARCHAR(500) NOT NULL,
 created_at DATETIME NOT NULL,
 INDEX(room_id), INDEX(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS calls (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 caller_id INT UNSIGNED NOT NULL,
 callee_id INT UNSIGNED NOT NULL,
 offer LONGTEXT,
 answer LONGTEXT,
 status ENUM('ringing','active','ended','rejected') NOT NULL DEFAULT 'ringing',
 created_at DATETIME NOT NULL,
 answered_at DATETIME DEFAULT NULL,
 ended_at DATETIME DEFAULT NULL,
 INDEX(caller_id), INDEX(callee_id), INDEX(status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS reports (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 reporter_id INT UNSIGNED NOT NULL,
 target_user_id INT UNSIGNED NOT NULL,
 reason VARCHAR(500) NOT NULL,
 status ENUM('open','closed') NOT NULL DEFAULT 'open',
 created_at DATETIME NOT NULL,
 INDEX(status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS admins (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(100) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 created_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
